apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  {{ if .Values.mysql.secrets.dbname }}
  dbname:   {{ .Values.mysql.secrets.dbname | b64enc }}
  {{ else }}
  dbname: {{ randAlphaNum 12 | b64enc }}
  {{ end }}
  {{ if .Values.mysql.secrets.user }}
  user:     {{ .Values.mysql.secrets.user   | b64enc }}
  {{ else }}
  user: {{ randAlphaNum 12 | b64enc }}
  {{ end }}
  {{ if .Values.mysql.secrets.password }}
  password: {{ .Values.mysql.secrets.password | b64enc }}
  {{ else }}
  password: {{ randAlphaNum 12 | b64enc }}
  {{ end }}
  {{ if .Values.mysql.secrets.rootpw }}
  rootpassword:  {{ .Values.mysql.secrets.rootpw | b64enc }}
  {{ else }}
  rootpw: {{ randAlphaNum 12 | b64enc }}
  {{ end }}
