apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mysql.persistence.pvcname }}
spec:
  accessModes:
    - {{ .Values.mysql.persistence.accessMode }}
  storageClassName: {{ .Values.mysql.persistence.stoaregClass }}
  resources:
    requests:
      storage: {{ .Values.mysql.persistence.size }}
