apiVersion: v1
kind: Service
metadata:
  name: {{ template "myapplication.fullname" . }}
  labels:
    app: {{ template "myapplication.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.mysql.service.type }}
  ports:
    - port: {{ .Values.mysql.service.port }}
      targetPort: {{ .Values.mysql.service.targetPort }}
  selector:
    app: {{ template "myapplication.name" . }}
