apiVersion: v1
kind: Service
metadata:
  name: {{ template "webserver.fullname" . }}
  labels:
    app: {{ template "webserver.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.webserver.service.type }}
  ports:
    - port: {{ .Values.webserver.service.port }}
      protocol: TCP
  selector:
    app: {{ template "webserver.fullname" . }}
